# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for google-analytics-mcp
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy source code
COPY src ./src

# Default command
CMD ["node", "src/index.js"]
